---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Bassist and Author Daniel Stotz"
keywords:    "prunner, double bass method book, scales, arpeggios, fixed-position, thesis, dissertation, bow rehair, phoenix, arizona"
description: "Joseph Prunnerâ€™s bass method books for scales and arpeggios; how to plan, complete and monetize your dissertation"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  duckgreen: '#3d731e'
  gold:      '#decb23'
  lime:      '#add936'
  sunkist:   '#ffe436'
  turquoise: '#0fbfcf'
  
  ### link ids ###
[link01]: http://amzn.to/1eICsvo "Volume I: Major/Minor Scales and Arpeggios (327 pp.)"

[link02]: http://amzn.to/1LQBkk2 "Volume II: Chromatic Scales and Fixed-Position Major and Minor Scales and Arpeggios"

[link03]: http://amzn.to/1HWCfB5 "Volume I & II"